### ISSUE TITLE
Make Bert.RateLimiters .netstandard2.0-compliant

### ISSUE THREAD

**Issue by mtikilay** [robertmircea/RateLimiters#11]
Hello,

This is not an issue with any fuctionality per se, but with the project setup. I've put together a PR (see https://github.com/robertmircea/RateLimiters/pull/10) to move to the new SDK project style and to target .netstandard2.0. Currently, using RateLimiters results in warnings about the wrong framework being targetted and it would be nice to get rid of those. This PR achives this. Can I ask you to merge it in if you're happy with it, and to republish the nuget package, please?

Thanks,
MT

**Comment by robertmircea** [comment]
Thanks for the PR. I've merged it and published a new version on nuget.org. I've also introduced Nuke Build as a build system for the library for easier versioning and publishing of new releases.

**Comment by mtikilay** [comment]
Thank you very much, have confirmed it all works and builds .netstandard2.0/netcore apps without grumbling!
