### ISSUE TITLE
WaitTime is always zero when ShouldThrottle() returns true

### ISSUE THREAD

**Issue by damianh** [robertmircea/RateLimiters#3]
Hi, am looking to adopt this library into my [LimitsMiddleware](https://github.com/damianh/LimitsMiddleware). It appears though that the wait time is always zero in the case that throttling should be applied: https://github.com/robertmircea/RateLimiters/blob/master/src/Bert.RateLimiters/TokenBucket.cs#L41

I also can't find anywhere where the value of the wait time is asserted in the tests https://github.com/robertmircea/RateLimiters/blob/master/src/Bert.RateLimiters.Tests/FixedTokenBucketTests.cs

I accept that I may be misunderstanding how this is meant to work, but I was expecting a value here. Is this correct?

Cheers.

**Comment by robertmircea** [comment]
Published a new version with fixes.
